---
- name: nginx Install - setup nginx repository
  yum_repository:
    name: nginx
    description: nginx repository
    baseurl: "http://nginx.org/packages/{{ ansible_distribution | lower }}/$releasever/$basearch"
    gpgkey: "http://nginx.org/keys/nginx_signing.key"
    gpgcheck: yes
    enabled: yes

- name: "nginx Install - install {{ nginx_package_name }}"
  yum:
    name: "{{ nginx_package_name }}"
    state: installed
    enablerepo: nginx

- name: nginx Install - create /etc/nginx/{sites-available sites-enabled}
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
  with_items:
    - '/etc/nginx/sites-available'
    - '/etc/nginx/sites-enabled'
