---
# Variable setup
- include: variable_setup.yml

# OS Specific installation
- include: "install_{{ ansible_distribution | lower }}.yml"

# Configure nginx
- include: configure.yml

# Ensure the service is started and enabled
- include: service.yml
