---
- name: Provision a Docker Playground
  hosts: all
  become: yes

  tasks:
    - name: add custom repo for ruby
      yum_repository:
        name: fnrpms
        description: s3 bucket full of rpms
        baseurl: "http://fnrpms.s3-website-us-east-1.amazonaws.com/$releasever/$basearch"
        gpgcheck: no
        enabled: yes

    - name: enable epel
      yum:
        name: epel-release
        state: present

    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - ansible
        - docker
        - gcc
        - git
        - libffi-devel
        - libyaml-devel
        - openssl-devel
        - python-devel
        - python-pip
        - ruby

    - name: install gems
      gem:
        name: "{{ item }}"
        state: present
      with_items:
        - rake
        - rubocop
        - serverspec

    - name: install pip things
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-py
        - testinfra
        - "git+https://github.com/metacloud/molecule.git#egg=molecule"

    - name: create the docker group
      group:
        name: docker
        state: present
      register: docker_group

    - name: add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
      register: vagrant_user

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: restart docker if necessary
      service:
        name: docker
        state: restarted
      when: docker_group.changed or vagrant_user.changed
